### ISSUE TITLE
UX Sp1 (Task)

### ISSUE THREAD

**Issue by julieguthrie** [nationalarchives/ds-alpha-engagement-vision#10]
### STAGE ONE
- [ ] Desk research/competitor review
- [ ] Define Users/User group - TEAM
- [ ] Define the business case (and ensure work aligns with this) - PRODUCT OWNER/DELIVERY MANAGER
- [ ] Define hypothesis/product/service - TEAM
- [ ] Define User Goals - TEAM
- [ ] Define Current user journey (and potential user journey) incl pain points - UX and TEAM

### STAGE TWO
In all phases, Explore to Live
- [ ] Ensure research and design are inclusive (WCAG 2.1 guidelines) TEAM (UX led)
- [ ] Design research plan (methods, tasks etc ) - UX
- [ ] Consider any laws or policies that may apply (incl GDPR) TEAM
- [ ] Clarify and agree any objectives for user testing - TEAM
- [ ] Define metrics for testing - UX and TEAM
- [ ] Consider assisted digital - TEAM

**Comment by jklepfer** [comment]
Also: 

- Make sure we are asking the right questions 

- Make sure we are clear what we are hoping to come out of this phase with.
